language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls 
  - pip install nose
before_script:
  - psql -c "CREATE DATABASE test_weconnect;" -U postgres
  - psql -c "CREATE USER weconnect WITH PASSWORD 'weconnect';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_weconnect TO weconnect;" -U postgres  
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls